server:
  host: "0.0.0.0"
  port: 8080

jwt:
  secret: "very_strong_secret_here"
  expireHour: 1
  refreshHour: 168

database:
  dialect: "sqlite"
  dsn: "data.db"

redis:
  addr: ""
  password: ""
  db: 0
